### ISSUE TITLE
Error in reading nwb files in matnwb

### ISSUE THREAD

**Issue by cmikkelsen** [dandi/helpdesk#121]
When we are trying to use nwbRead to open the data from this experiment: https://dandiarchive.org/dandiset/000114?search=oxytocin%20neurons%20social%20transmission&pos=1 we are getting an error using matnwb, " Unable to resolve the name 'types.hdmf_experimental.DynamicTableRegion'. " when trying to load the data .  It seems to be occuring for a number of files, but we are able to open data from other dandisets successfully. Thank you for any guidance on how to resolve this issue!

**Comment by yarikoptic** [comment]
attn @lawrence-mbf @bendichter @rly

**Comment by lawrence-mbf** [comment]
Without access to a computer, my guess would be that this file is missing a schema. If so (and using the most recent matnwb version), calling

`generateCore(util.getSchemaVersion(<filename>))`

Should allow you to then read the file. If that throws please let us know.

,Lawrence

Nov 23, 2023 06:57:01 Yaroslav Halchenko ***@***.***>:

**Comment by lawrence-mbf** [comment]
Submit your images today! An image contest celebrating the beauty of the brain The NeuroArt image contest is a celebration of the beauty of the brain. It's a place to share your view of the brain - whether you use stains or dyes to visualize neurons under a microscope, use fMRI to analyze brain activity, or put a pencil to a piece of paper and draw your perspective. Any image, photo, drawing, or painting of the brain is accepted.   December Image Contest Now Open Share your view of the brain with us!  Enter the Contest   How it works NeuroArt is a monthly contest with 2 awards given each month. You can enter up to 3 images each month. Anyone over the age of 18 with an interest in neuroscience can enter.   There are two awards given each month: 1. Juror's Choice (chosen by our judging panel of scientists and artists) 2. People's Choice (image with the most number of votes)   The Juror's Choice winner becomes eligible to have their image on the cover of the Journal of Neuroscience Research. People's Choice winner gets $250 towards the purchase of MBF Bioscience software or a free 3D printed brass neuron. Read all Rules and Prizes   Here's how to enter:   Step 1. Go to the December NeuroArt Contest Step 2. Submit up to 3 images, making sure images meet these requirements: Image must be free of labels such as scale bars, etc. Image must be submitted in JPEG or PNG format. Please note: Each contestant should also have a copy of their JPEG or PNG images available in 810 x 612 points (3375 x 2550 pixels) at a resolution of 300 dpi in TIFF format. The journal cover winner will need to submit their image in this TIFF format to appear on the cover of Journal of Neuroscience Research. Step 3. Share your images with friends. Winners will be announced early January. We request you to include as much information as possible about the image. For example: Microscopy methods used, staining techniques, region(s) of brain, neuron type(s), species and more.   Enjoy stunning images submitted by neuroscientists from around the world You are welcome to download this wallpaper collection to visually enhance your desktop. MBF Bioscience is glad to share these extraordinary images to celebrate the beauty of the brain. Enjoy! Free Download NeuroArt on Instagram Follow MBF Bioscience @mbfbioscience on Instagram to see the NeuroArt contest entries. Comment on images You can now ask questions and leave comments on images at neuroart.com.  Invite friends and colleagues to enter the contest. The more people who share their unique view of the brain, the better the contest will be.  www.neuroart.com   MBF Bioscience | 1-802-288-9290 | ***@***.***             MBF Bioscience | 185 Allen Brook Lane, Williston, VT 05495 Unsubscribe ***@***.*** Update Profile | Our Privacy Policy | Constant Contact Data Notice Sent by ***@***.*** powered by Try email marketing for free today!

**Comment by rly** [comment]
It looks like the issue has been fixed in the latest draft version of the dandiset: https://dandiarchive.org/dandiset/000114/draft so I think this issue can be closed.
