### ISSUE TITLE
Support Zarr datasets

### ISSUE THREAD

**Issue by satra** [dandi/helpdesk#13]
For the microscopy data in DANDI, there is a need to consider the [NGFF](https://ngff.openmicroscopy.org/latest/), which uses [Zarr](https://zarr.readthedocs.io/en/stable/) as a backend. 

The design for this feature is being discussed here: https://github.com/dandi/dandi-api/pull/295

**Comment by yarikoptic** [comment]
we have zarrs supported in a limited (no publishing) form. Details should be ironed out in other issues AFAIK.
