### ISSUE TITLE
Page selection buttons does not behave correctly on the Dandi Archive website

### ISSUE THREAD

**Issue by shixnya** [dandi/helpdesk#134]
### Bug description

When browsing the data, the page selection buttons becomes a single item box, preventing selecting other pages.

#### Expected behaviour

The page selection boxes should keep the same number of items as I browse different pages.

#### Actual behaviour

The page selection boxes only shows "1" and does not let me select any other page. Also, the "Next" button is no active. I can only go back to the first page.

### How to reproduce

1. Go to https://dandiarchive.org
2. click "dandisets"
3. click any of the page selection boxes at the bottom of the page.
4. You'll see only one item in the page selection box.

### Your personal set up

 - OS:
 
MacOS 14.4.1
 - Browser:
 
Safari 17.4.1
Chrome 123.0.6312.107
 - Version(s):
 
v0.3.84

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by shixnya** [comment]
This is before selecting an item in the bottom box.



<img width="692" alt="Screenshot 2024-05-01 at 12 13 22 PM" src="https://github.com/dandi/helpdesk/assets/4859385/72e58f5e-ded8-4ffd-b660-2cc801cc14db">




This is after selecting an item in the box. All the options other than "1" disappears.




<img width="692" alt="Screenshot 2024-05-01 at 12 13 28 PM" src="https://github.com/dandi/helpdesk/assets/4859385/6e7c9d79-ad1b-4a22-90db-f429be114186">

**Comment by yarikoptic** [comment]
sorry -- known issue 

- https://github.com/dandi/dandi-archive/issues/1917

attn @waxlamp
