### ISSUE TITLE
I do not have an NIH number as I am Canadian, how can I embargo my data

### ISSUE THREAD

**Issue by AngCamp** [dandi/helpdesk#148]
As in the title, I want to share my data on Dandi but I am a Canadian researcher and I do not have an NIH grant number which is required to embargo my data.  How can I get around this if I want to embargo my data?

**Comment by kabilar** [comment]
Thanks for the report @AngCamp.  As a temporary workaround, please enter `1 R01 CA 123456-01` in the `NIH Award Number` field and enter the Gov of Can award number in the `Description` field.  Also please make sure to read the terms/policies around embargo.  We will work to find a more permanent solution.
