### ISSUE TITLE
need help ending embargo

### ISSUE THREAD

**Issue by rachelirenewilson** [dandi/helpdesk#158]
I want to make our dandiset public now. However, it seems I can't, because of this error:
"This dandiset has 1 metadata validation error(s). access: An embargo end date is required for NIH awards to be in compliance with NIH resource sharing policy."
How can I fix this? I don't see where to enter (or change) the embargo end date.

**Comment by kabilar** [comment]
Hi @rachelirenewilson, which Dandiset has this error?

**Comment by rachelirenewilson** [comment]
It's this Dandiset: https://dandiarchive.org/dandiset/000289/draft
Note that Access Information: dandi:OpenAccess
So I can't figure out what the problem is, exactly.

**Comment by yarikoptic** [comment]
was it ever embargoed? when did it go through unembargo procedure? 
(may be metadata re-validation failed to trigger during that, attn @jjnesbitt , and thus validation error is from the past when it was still embargoed...?)

**Comment by satra** [comment]
I reinitiated validation by fixing a spelling in one of the study targets. It's ready for publishing.

**Comment by kabilar** [comment]
Thanks team.

Hi @rachelirenewilson, I saw that you were able to publish a version today.  I just want to confirm that this issue is now resolved?  Thanks.

**Comment by kabilar** [comment]
Closing this issue as I believe it is now resolved.  Please reopen if it is not.
