### ISSUE TITLE
Add version'ed dandiset permalink redirection to identifiers.org

### ISSUE THREAD

**Issue by yarikoptic** [dandi/helpdesk#29]
I think it would be nice to have permalinks at identifiers.org for releases, although nohow crucial (we have DOIs; so could be closed if that would be the decision). ATM https://identifiers.org/DANDI:000039/0.210902.2328 leads to error

> INVALID resolution request for 'DANDI:000039/0.210902.2328', due to 'Resolution request 'DANDI:000039/0.210902.2328' is NOT ABOUT A NAMESPACE; UNKNOWN namespace 'DANDI' when verifying local ID '000039/0.210902.2328''

**Comment by satra** [comment]
this works: https://identifiers.org/dandi:000039/0.210902.2328

filed an issue via email with identifiers.org

**Comment by satra** [comment]
the resolver does not complain, but will error still. have not heard anything back from identifiers.org.

![image](https://user-images.githubusercontent.com/184063/137234715-9f7d8b23-ae3c-448e-833a-2c89c18139b5.png)

**Comment by satra** [comment]
this has now been resolved both capitalized and lower case prefix works.
